### ISSUE TITLE
Configuração do Ambiente

### ISSUE THREAD

**Issue by joaomedeiros95** [devfest-ufrn/SmartClass#6]

**Comment by PedroVictorB** [comment]
1. Criar uma máquina virtual (Ubuntu 16.04)
2. Instalar Docker
3. Instalar ORION (docker) *
4. Instalar Wirecloud (docker) *

*Pode ser feito por docker-compose

**Comment by PedroVictorB** [comment]
@joaomedeiros95 @Stefano10 Máquina pronta. Ip está no slack.
