### ISSUE TITLE
Implementar o backend

### ISSUE THREAD

**Issue by joaomedeiros95** [devfest-ufrn/SmartClass#7]
Implementação da solução utilizando Fiware

**Comment by PedroVictorB** [comment]
1. Criar uma máquina virtual (Ubuntu 16.04)
2. Instalar Docker
4. Instalar ORION (docker) *
5. Instalar Wirecloud (docker) *

* Pode ser feito por docker-compose

**Comment by PedroVictorB** [comment]
1. Entidades Sala no backend ORION foram criadas;
2. NGSI Proxy foi instalado na vm da google (Necessário para o funcionamento do NGSI Source do Wirecloud);
3. OPERATOR (NGSI Source) no Wirecloud foi instalado e configurado.
